### ISSUE TITLE
Update the product metadata fields

### ISSUE THREAD

**Issue by mwest007** [punch-mission/punchbowl#195]
Notes:

General comments
----------------
FILENAME = not generated
CAR_ROT not being populated
RSUN_ARC = None
SOLAR_EP = None

The following cannot be constructed
-----------------------------------
PSM - Cannot construct
CSM - Cannot construct

TITLE
-----
SM1,2,3,4 - "PUNCH Level-1 ?FI-? Polarized Additive Stray Light Model"
SZ1,2,3,4 - "PUNCH Level-1 ?FI-? Polarized Additive Stray Light Model"
SP1,2,3,4 - "PUNCH Level-1 ?FI-? Polarized Additive Stray Light Model"
SR1,2,3,4 - "PUNCH Level-1 ?FI-? Unpolarized Additive Stray Light Model"
VAN - "PUNCH Level-3 Derived NFI Wind Velocity"
VAM - "PUNCH Level-3 Derived Mosaic Wind Velocity"

FILENAME
--------
Not being populated in any file

OBSTYPE
-------
VAM - Not populated
VAN - Not populated
PLM - Not populated
VOM - Not populated
PTM L2/QL/L3 - "Polarized mosaic image"
CTM L2/QL/L3 - "Unpolarized mosaic image"

OBS-MODE
--------
ST4
GM1,2,3,4 - Polar_MZP
GZ1,2,3,4 - Polar_MZP
GP1,2,3,4 - Polar_MZP
GR1,2,3,4 - Unpolarized
SM1,2,3,4 - Polar_MZP
SZ1,2,3,4 - Polar_MZP
SP1,2,3,4 - Polar_MZP
SR1,2,3,4 - Unpolarized

OBSLAYR1
--------
The following are not populated: ST4, DK1, DK2, DK3, DK4, DY1, DY2, DY3, DY4, OV1, OV2, OV3, OV4, XI1, XI2, XI3, XI4, BD1, BD2, BD3, BD4, FQ1, FQ2, FQ3, FQ4, RG1, RG2, RG3, RG4, CTM, CNN, CFM, CFN, CTM, CNN, CFM, CFN, CTM, CNN, CFM, CFN, CSM, CTM, CNN, VAM, VAN, CAM, CAN, PLM, VOM
We have a code -999 for clear, why not for the combined MZP?

FILTER
------
ST - ST
GM1,2,3,4 - P1
GZ1,2,3,4 - P2
GP1,2,3,4 - P3
GR1,2,3,4 - Clear
SM1,2,3,4 - P1
SZ1,2,3,4 - P2
SP1,2,3,4 - P3
SR1,2,3,4 - Clear

The following are not populated: ST4, DK1, DK2, DK3, DK4, DY1, DY2, DY3, DY4, OV1, OV2, OV3, OV4, XI1, XI2, XI3, XI4, BD1, BD2, BD3, BD4, FQ1, FQ2, FQ3, FQ4, RG1, RG2, RG3, RG4, PTM, PNN, CTM, CNN, CFM, CFN, CTM, CNN, PFM, PFN, PTM, PNN, CFM, CFN, CTM, CNN, PFM, PFN, CFM, CFN, PSM, CSM, PTM, PNN, CTM, CNN, VAM, VAN, PAM, PAN, CAM, CAN, PLM, VOM

CRPIX1,CRPIX2,CRPIX2A,CRPIX2A
-----------------------------
These should have consistent values, 0 or 2047.5, the Mosaics DO NOT go to 4096. Some have CRPIX1A 0, some have 2047.5.

CNAME3
------
CTM and CNN not populated

CTYPE
-----
Does this change as we transform?

NAXIS3
------
PFM - not filled
PFN - not filled
PTM - not filled
PNN - not filled

CDELT1A & CDELT2A
-----------------
Always -0.0225 & 0.0225
This is not correct for ST4
QuickPUNCH are downsampled, so this should be bigger.

CRVAL1 & CRVAL2
---------------
Always 0
ST4 does not have CRVAL2

LONPOLE
-------
Always 180

CUNIT2
------
ST4 does not have CUNIT2

LATPOLE
-------
Always 90

DETECTOR
--------
Always CCD 2Kx2K,
This should be more specific, specify when its a combination in mosaics.
Should not be in any product after L2

REGION
------
Always 1

READOUT0
--------
Always 3

PXBEG1 & DSTART1 & DSTART1
--------------------------
Always 1, should this match CRPIX1A?
This should match DSTART1

PXEND1 & DSTOP1 & DSTOP2
------------------------
Always 2048, should be 1024 for QuickPUNCH, and 4096 for mosaics
This should match DSTOP1

The following are not filled in any value
-----------------------------------------
PIPEVRSN
FILE_RAW
DATE-BEG
DATE-AVG
DATE-END
DATE
OBSLAYR1
CALCF
CALVI
CALPSF
CALPM
CALSL
SQRTCODE
COMPRESS
RSUN_ARC
SOLAR_EP
GEOD_LAT
GEOD_LON
GEOD_ALT
LOS_ALT
HGLT_OBS
HGLN_OBS
CRLT_OBS
CRLN_OBS
DSUN_OBS
HEEX_OBS
HEEY_OBS
HEEZ_OBS
HCIX_OBS
HCIY_OBS
HCIZ_OBS
HCIX_VOB
HCIY_VOB
HCIZ_VOB
HAEX_OBS
HAEY_OBS
HAEZ_OBS
HEQX_OBS
HEQY_OBS
HEQZ_OBS

BUNIT
-----
Is the mean solar brightness always the same for polarized data?

RSUN_ARC & RSUN_REF
-------------------
Do we need both?
RSUN_ARC [arcsec] photospheric solar radius 952.565

BSUN_DEF
--------
No value = PM1, PM2, PM3, PM4, PZ1, PZ2, PZ3, PZ4, PP1, PP2, PP3, PP4, CR1, CR2, CR3, CR4, PX1, PX2, PX3, PX4, ST4, DK1, DK2, DK3, DK4, DY1, DY2, DY3, DY4, OV1, OV2, OV3, OV4, XI1, XI2, XI3, XI4

SOLAR_EP
--------
5.92376011723103 / [deg] s/c ecliptic North to solar North angle

To check
--------
CRPIX1 = 0.0  - This is a float. Also the reference pixels are 1->2048
CRPIX2 = 0.0
CRPIX1A = 2047.5
CRPIX2A = 2047.5
CRVAL1 = 0.0
CRVAL2 = 0.0
CRVAL1A = 0.0
CRVAL2A = 0.0

To check
--------
NAXIS
NAXIS1
NAXIS2
TITLE
DESCRPTN
OBSLAYR1
INSTRUME
TELESCOP

SQRTCODE
--------
Do we need to describe this?

COMPRESS & COMP_RAT
-------------------
Needs to be filled and the ratio updated

LEDDAC
------
Sould this be on for STIM LAMP?

RAWBITS
-------
Is this always 16? Should this be 19 for L0 NFI?

NBIN1 & NBIN2
-------------
What are these for?

IMGCTR
------
This is the Sequential counter since the last reboot, do we have this.

No value
--------
OBSLAYR2, OBSLAYR3, CRPIX3, PC1_3, PC2_3, PC3_1, PC3_2, PC3_3, CDELT3, CUNIT3, CTYPE3, CRVAL3, CRPIX3A, PC1_3A, PC2_3A, PC3_1A, PC3_2A, PC3_3A, CDELT3A, CUNIT3A, CTYPE3A, CRVAL3A

CUNIT3 & CUNIT3A
----------------
Not populated at all

Questions
---------
Should PLM have NAXIS=3?
Why do we have OBS-MODE and OBSLAYR1
FQ1,2,3,4 has a comment that is too long and needs to be truncated.
Will any of the QuickLOOK products have a meta data?
Are CTYPE1 & 2 correct early on
CTM & CNN do not have CNAME3
Are all CNAME3 'STOKES'
PXEND should go in mosaic L2

**Comment by jmbhughes** [comment]
I'm going to close this since Chris just checked updated metadata.
