### ISSUE TITLE
We can speed up mosaic building

### ISSUE THREAD

**Issue by svank** [punch-mission/punchbowl#307]
Right now when building mosaics, each input image is reprojected into the full output frame. Each input (or its bounding box) spans maybe a third of the output frame, so we're doing about 3x more WCS calculations than we need to. By reprojecting into a cutout of the output frame (equal to the bounding box of the input image's projection) and then combing those into the full mosaics, we can probably speed up the mosaic building by 3x.

This can be done by first projecting a bunch of points along the edges of the input image into the output frame and finding the min/max coordinates of those points. (Yesterday I wrote code to do that for the helio->celestial reprojections in L3).

`reproject` also has `reproject_and_coadd`, which takes in multiple images and builds a mosiac, and it does this bounding-box calculation automatically. It has a few modes for how to handle the overlap region between images---not sure if there's one that does what PUNCH wants. (Also, this probably can't handle stacked input images)

(Ultimately, I feel like this is a feature that should be added to `reproject` itself for `reproject_adaptive` et al.)

Sounds like we can also speed it up by stacking the uncertainty on the data, to avoid redoing the coordinate conversions when reprojecting them separately.

**Comment by jmbhughes** [comment]
Closed in #310

**Comment by jmbhughes** [comment]
Reopening because there's more we can do.
